<?php

namespace Container3zB1ifg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GQ7HbuPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GQ7HbuP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GQ7HbuP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sortie' => ['privates', '.errored..service_locator.GQ7HbuP.App\\Entity\\Sortie', NULL, 'Cannot autowire service ".service_locator.GQ7HbuP": it needs an instance of "App\\Entity\\Sortie" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'sortie' => 'App\\Entity\\Sortie',
        ]);
    }
}
