<?php

namespace Container3zB1ifg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSortieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GQ7HbuP.App\Entity\Sortie' shared service.
     *
     * @return \App\Entity\Sortie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GQ7HbuP": it needs an instance of "App\\Entity\\Sortie" but this type has been excluded in "config/services.yaml".');
    }
}
