<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLc0WIGY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLc0WIGY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLc0WIGY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLc0WIGY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLc0WIGY\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lc0WIGY',
    'container.build_id' => '8057e84c',
    'container.build_time' => 1710422340,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLc0WIGY');
